[package]
name = "rv-repo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Repository and metadata fetching for Raeva"

[dependencies]
rv-config.workspace = true
rv-maven-model.workspace = true
rv-store.workspace = true
rv-version.workspace = true

anyhow.workspace = true
backon.workspace = true
chrono.workspace = true
bytes.workspace = true
fs2.workspace = true
futures.workspace = true
futures-core.workspace = true
hex.workspace = true
quick-xml.workspace = true
r2d2.workspace = true
r2d2_sqlite.workspace = true
regex.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
secrecy.workspace = true
serde.workspace = true
sha1.workspace = true
sha2.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
rustls.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true
