<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>repo-app</artifactId>
  <version>1</version>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>repo-owner</artifactId>
      <version>1</version>
    </dependency>
  </dependencies>
</project>
