<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>b</artifactId>
  <version>1</version>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>a</artifactId>
      <version>1</version>
    </dependency>
  </dependencies>
</project>
